"""
How to Define a Class in Python? What Is Self? Give An Example Of A Python Class ?

A Class is like an object constructor, or a "blueprint" for creating objects.
---> Create a Class. To create a class, use the keyword class : ...
---> Create Object. Now we can use the class named MyClass to create objects: ...
---> The self Parameter. ...
---> Modify Object Properties. ...
---> Delete Object Properties. ...
---> Delete Objects.

"""